### ISSUE TITLE
Expose Firestore query errors

### ISSUE THREAD

**Issue by sampl** [green-arrow/react-firestore#12]
First of all, thanks for releasing react-firestore. It's the perfect way to bring my two favorite tools together, and the API you chose is spot on.

A feature request: it would be great if each component could pass Firebase errors when they occur. This can happen if you try to query content but don't have the right permissions, for example.

Something like:

```
<FirestoreCollection
  path="stories"
  sort="publishedDate:desc,authorName"
  render={({ isLoading, data, error }) => {
    if (error) return `Whoops! ${error.message}`
    
    return isLoading ? (
      <Loading />
    ) : (
      <div>
        <h1>Stories</h1>
        <ul>
          {data.map(story => (
            <li key={story.id}>
              {story.title} - {story.authorName}
            </li>
          ))}
        </ul>
      </div>
    );
  }}
/>
```

I've built something similar here: https://github.com/sampl/firefly/blob/master/src/data/PostsProvider.js

**Comment by green-arrow** [comment]
@sampl - I think this is a good idea. I'll try to get to this sometime this week. Feel free to submit a PR if you want / have time 😄

**Comment by sampl** [comment]
Woohoo, thank you! I'll work on #14 first and check back.

**Comment by sampl** [comment]
@green-arrow I got this far: https://github.com/sampl/react-firestore/commit/55bdb23e38751379a86246a6e9b1b1e4f0714a98

It works, but existing tests aren't passing (and there are no new tests to cover error use cases).

I think I've gotten as far as I can get it. If anyone wants to finish it off, I'd really appreciate it!
