### ISSUE TITLE
Accept Number as valid type for filter array

### ISSUE THREAD

**Issue by lrholmes** [green-arrow/react-firestore#16]
Currently using a number to filter a collection query causes a PropType error, when it is actually valid. In fact, changing the number to a string to silence the warning breaks the filter.

I'm happy to contribute the fix for this, if you can confirm that this project is still being maintained? Hope so!

**Comment by green-arrow** [comment]
@lrholmes - definitely still maintained, I'd be happy to merge a PR for this!
