### ISSUE TITLE
Errors from queries

### ISSUE THREAD

**Issue by TheNextBid** [green-arrow/react-firestore#28]
Sorry for not using the issue template... I just have a really small question. I'm using the library for some queries and stuff and I wanted to show a message when an error popped up. I noticed [this awesome commit of like 12 days ago](https://github.com/green-arrow/react-firestore/commit/d78f4b3d06cadeb1e6e426de050f6c0a737fc889) which solves this issue and I wonder when this will be deployed to NPM and everything. Thanks!

**Comment by sampl** [comment]
@TheNextBid I think it’s live already, just undocumented still

**Comment by TheNextBid** [comment]
@sampl Hmmm... At NPM it's version 0.8.1, which is the same of three months ago, without this commit

**Comment by green-arrow** [comment]
@TheNextBid @sampl - sorry about this. Looks like there was a hang up with semantic release. I never updated TravisCI with a new NPM token. 

0.9.0 should be live now. 

Thanks for bringing this up!

**Comment by TheNextBid** [comment]
@green-arrow okey this is weird... I can see v0.9.0 at the readme badge from shields.io, but at NPM itself it's still not published

![image](https://user-images.githubusercontent.com/38106486/44790893-f8dbc880-ab65-11e8-9117-84f85188ab65.png)

**Comment by TheNextBid** [comment]
@green-arrow @sampl wow I just noticed that the [NPM version](https://www.npmjs.com/package/react-firestore) is still at 0.8.1 but the version published for [yarn](https://yarnpkg.com/en/package/react-firestore) is already at 0.9.0. Well... I feel lucky for using yarn, but I guess someone might want to take a look at this 🙈
