### ISSUE TITLE
timestampsInSnapshots error in console log

### ISSUE THREAD

**Issue by raihanflores** [green-arrow/react-firestore#29]
* `react-firestore` version: 0.9.0
* `node` version: v10.1.0
* `npm` (or `yarn`) version: 6.1.0

I am getting a console error regarding timestampsInSnapshots and i it is a big bright red wall of text. Where should I set it?

Here is a basic project using `react-firestore`

[https://ryannflores@bitbucket.org/ryannflores/react-firestore.git](url)

**Comment by lauris** [comment]
The solution for this can actually be found in the error message:

```
const firestore = firebase.firestore();
const settings = {timestampsInSnapshots: true};
firestore.settings(settings);
```
