### ISSUE TITLE
Guide how to combine collections

### ISSUE THREAD

**Issue by barbush** [green-arrow/react-firestore#31]
Hi @green-arrow, this is a truly awesome project!

I wanted to ask, is there any place in the docs which would guide me towards combining collections?

For instance, in the case where I have two collections. One has property 'collection1.userId' and collection 2 also contains this: 'collection2.userId'.

I would like to query all of collection1 and combine to each document, the matching document from collection2. 

In super rough pseudo code, the idea is:

```
   FirestoreCollection='users'
    userId
       firstName
       lastName
    FirestoreCollection='relational-collection'
       userId=='userId' 
          get related document
   ```

**Comment by sampl** [comment]
Something like this? (Untested/slow/buggy):

```jsx
<FirestoreCollection path=“collection1”>
  { ({data}) => {
    const collection1 = data
    return <FirestoreCollection path=“collection2”>
      { ({data}) => {
        const collection2 = data

        // combine both collections
        const combinedItems = collection1.map(item1 => {
          const item2 = collection2.find(item => item.userId === item1.userId)
          return {
            ...originalItem,
            ...matchingItemFromCollection2,
          }
        })
        console.log(combinedItems)

      }}
    </FirestoreCollection>
  }}
</FirestoreCollection>
```

faster way: https://codereview.stackexchange.com/a/104683

**Comment by barbush** [comment]
Awesome thanks @sampl ! 

I'm gonna roll with this

**Comment by hegelstad** [comment]
I'd wish there was a better way than nesting collections. Something like a combine. I am pretty sure it's not very hard to do this ourselves, so I wonder if anyone know a good resource to learn that pattern?
