### ISSUE TITLE
New timestamp config throwing error on init

### ISSUE THREAD

**Issue by tommaitland** [green-arrow/react-firestore#33]
* `react-firestore` version: 0.10.1
* `firebase` version: 5.5.8
* `node` version: 8
* `npm` (or `yarn`) version: 1.7 yarn

Relevant code or config

```javascript
import firebase from '@firebase/app';
import '@firebase/firestore';
firebase.initializeApp(firebaseConfig);
<FirestoreProvider firebase={firebase} useTimestampsInSnapshots>
```

What you did:
It seems like the latest version of the package isn't initialising correctly due to how the timestamp settings are being set.

What happened:
Throwing the following error on load:

Firebase: firebase.firestore() takes either no argument or a Firebase App instance. (app/invalid-app-argument).
![image](https://user-images.githubusercontent.com/3466825/48409769-e3536380-e790-11e8-9696-d5c8d4eae291.png)

Suggested solution:
It seems to be caused by this line: https://github.com/green-arrow/react-firestore/blob/master/src/FirestoreProvider.js#L27

Untested, but I think it needs to be replaced with `firebase.firestore().settings({ timestampsInSnapshots: this.props.useTimestampsInSnapshots})` before Line 26

**Comment by green-arrow** [comment]
@tommaitland - Thanks for reporting this! It should be fixed in v0.10.2
