### ISSUE TITLE
firestoreDatabase children prop is null because firestore().settings() does not return firestore instance

### ISSUE THREAD

**Issue by hartym** [green-arrow/react-firestore#34]
Versions

* node v10.11.0
* yarn 1.10.1
* react-firestore@0.10.2
* firebase@5.5.8

Relevant code or config (meta code)

```javascript
let firebase = ...;
export default () => (
    <FirestoreProvider firebase={firebase}>
        <FirestoreCollection path={'mycollection'} ... />
    </FirestoreProvider>
)
```

What you did:

Following the readme instructions basically to simply render a FirestoreCollection somewhere under the FirestoreProvider.

What happened:

Blank screen, complaining for firestoreDatabase childProp being null although it's required.

Problem description:

Apparently, firebase's firestore api now returns null from the settings(...) call (which I guess was wrong before a certain version.

See https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore-types/index.d.ts#L96

Suggested solution:

Instead of returning from the .settings() call, just do it on its own line and return the firestore instance.

https://github.com/green-arrow/react-firestore/blob/master/src/FirestoreProvider.js#L28

(fix works locally when patching the provider code, will provide a simple pull request)

**Comment by wietsevenema** [comment]
Here's just to confirm that this issue also happens for me and merging this PR will fix it.
